"""PLCBF library for safe control using Control Barrier Functions."""

__version__ = "0.1.0"

# Shared, scenario-agnostic APIs; concrete robot implementations live in examples/.
from plcbf.benchmarking import (
    BenchmarkAggregate,
    BenchmarkOutcome,
    BenchmarkReportSchemaError,
    BenchmarkReportPaths,
    BenchmarkResult,
    LoadedBenchmarkReport,
    NumericSummary,
    aggregate_results,
    benchmark_report_from_json,
    benchmark_results_from_json,
    load_benchmark_report,
    load_benchmark_results,
    merge_benchmark_results,
    results_to_csv,
    results_to_json,
    results_to_markdown,
    write_benchmark_reports,
)
from plcbf.pcbf import PCBFBase
from plcbf.policy_library import (
    CBFHalfspace,
    ClippedPolygon2D,
    DecisionDiagnostics,
    PolicyCertificate,
    PolicyDecision,
    PolicyEvaluation,
    QPSolution,
    SelectionMode,
    box_halfspace_volume,
    cbf_halfspace,
    clip_rectangle_halfspaces,
    rectangle_halfspaces_area,
    select_policy,
    solve_box_halfspace_qp,
    solve_weighted_box_halfspaces_qp_2d,
)

__all__ = [
    "BenchmarkAggregate",
    "BenchmarkOutcome",
    "BenchmarkReportSchemaError",
    "BenchmarkReportPaths",
    "BenchmarkResult",
    "LoadedBenchmarkReport",
    "CBFHalfspace",
    "ClippedPolygon2D",
    "DecisionDiagnostics",
    "NumericSummary",
    "PCBFBase",
    "PolicyCertificate",
    "PolicyDecision",
    "PolicyEvaluation",
    "QPSolution",
    "SelectionMode",
    "aggregate_results",
    "benchmark_report_from_json",
    "benchmark_results_from_json",
    "box_halfspace_volume",
    "cbf_halfspace",
    "clip_rectangle_halfspaces",
    "load_benchmark_report",
    "load_benchmark_results",
    "merge_benchmark_results",
    "rectangle_halfspaces_area",
    "results_to_csv",
    "results_to_json",
    "results_to_markdown",
    "select_policy",
    "solve_box_halfspace_qp",
    "solve_weighted_box_halfspaces_qp_2d",
    "write_benchmark_reports",
]
